# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'VKApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VKApp
  pod 'Alamofire', '5.6.1' 
  pod 'RealmSwift', '~>10'
  pod 'SwiftKeychainWrapper'
  pod 'FirebaseAnalytics'
  pod 'FirebaseFirestore'
end
